## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN', 'NAME'], axis=1)

In [3]:
# Determine the number of unique values in each column.
unique_value_counts = application_df.nunique()

In [4]:
# Look at APPLICATION_TYPE value counts for binning
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff_value = 500

application_types_to_replace = application_type_counts[application_type_counts < cutoff_value].index.tolist()

for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app, "Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df['CLASSIFICATION'].value_counts()

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts_gt_1 = classification_counts[classification_counts > 1]
print(classification_counts_gt_1)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff_value = 1000

classifications_to_replace = classification_counts[classification_counts < cutoff_value].index.tolist()


# Replace in the DataFrame
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls, "Other")

# Check to make sure binning was successful
classification_value_counts = application_df['CLASSIFICATION'].value_counts()
print(classification_value_counts)

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df_encoded = pd.get_dummies(application_df)

application_df_encoded.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [10]:
# Split our preprocessed data into our features and target arrays
y = application_df_encoded["IS_SUCCESSFUL"]
X = application_df_encoded.drop("IS_SUCCESSFUL", axis=1)
# Split the preprocessed data into a training and testing dataset
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [12]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=80, input_dim=len(X_train_scaled[0]), activation="relu"))

# Second hidden layer (optional)
nn.add(tf.keras.layers.Dense(units=30, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                3520

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 5981 (23.36 KB)
Trainable params: 5981 (23.36 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [13]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [14]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 1s 633us/step - loss: 0.5712 - accuracy: 0.7193
Epoch 2/100
804/804 [==============================] - 0s 451us/step - loss: 0.5555 - accuracy: 0.7285
Epoch 3/100
804/804 [==============================] - 0s 444us/step - loss: 0.5518 - accuracy: 0.7317
Epoch 4/100
804/804 [==============================] - 0s 449us/step - loss: 0.5507 - accuracy: 0.7313
Epoch 5/100
804/804 [==============================] - 0s 446us/step - loss: 0.5494 - accuracy: 0.7318
Epoch 6/100
804/804 [==============================] - 0s 439us/step - loss: 0.5487 - accuracy: 0.7317
Epoch 7/100
804/804 [==============================] - 0s 437us/step - loss: 0.5480 - accuracy: 0.7313
Epoch 8/100
804/804 [==============================] - 0s 474us/step - loss: 0.5477 - accuracy: 0.7318
Epoch 9/100
804/804 [==============================] - 0s 447us/step - loss: 0.5468 - accuracy: 0.7318
Epoch 10/100
804/804 [==============================] - 0s 435us/step - loss: 0.5459 - accuracy: 0.7331
Epoch 11/100
804/804 [==============================] - 0s 436us/step - loss: 0.5458 - accuracy: 0.7321
Epoch 12/100
804/804 [==============================] - 0s 436us/step - loss: 0.5456 - accuracy: 0.7327
Epoch 13/100
804/804 [==============================] - 0s 440us/step - loss: 0.5450 - accuracy: 0.7336
Epoch 14/100
804/804 [==============================] - 0s 440us/step - loss: 0.5444 - accuracy: 0.7338
Epoch 15/100
804/804 [==============================] - 0s 480us/step - loss: 0.5444 - accuracy: 0.7345
Epoch 16/100
804/804 [==============================] - 0s 437us/step - loss: 0.5440 - accuracy: 0.7350
Epoch 17/100
804/804 [==============================] - 0s 444us/step - loss: 0.5436 - accuracy: 0.7354
Epoch 18/100
804/804 [==============================] - 0s 435us/step - loss: 0.5438 - accuracy: 0.7347
Epoch 19/100
804/804 [==============================] - 0s 438us/step - loss: 0.5432 - accuracy: 0.7351
Epoch 20/100
804/804 [==============================] - 0s 433us/step - loss: 0.5421 - accuracy: 0.7355
Epoch 21/100
804/804 [==============================] - 0s 441us/step - loss: 0.5423 - accuracy: 0.7367
Epoch 22/100
804/804 [==============================] - 0s 468us/step - loss: 0.5425 - accuracy: 0.7353
Epoch 23/100
804/804 [==============================] - 0s 435us/step - loss: 0.5422 - accuracy: 0.7360
Epoch 24/100
804/804 [==============================] - 0s 434us/step - loss: 0.5415 - accuracy: 0.7360
Epoch 25/100
804/804 [==============================] - 0s 434us/step - loss: 0.5414 - accuracy: 0.7363
Epoch 26/100
804/804 [==============================] - 0s 435us/step - loss: 0.5412 - accuracy: 0.7369
Epoch 27/100
804/804 [==============================] - 0s 437us/step - loss: 0.5415 - accuracy: 0.7366
Epoch 28/100
804/804 [==============================] - 0s 436us/step - loss: 0.5408 - accuracy: 0.7362
Epoch 29/100
804/804 [==============================] - 0s 471us/step - loss: 0.5407 - accuracy: 0.7362
Epoch 30/100
804/804 [==============================] - 0s 435us/step - loss: 0.5406 - accuracy: 0.7364
Epoch 31/100
804/804 [==============================] - 0s 436us/step - loss: 0.5405 - accuracy: 0.7374
Epoch 32/100
804/804 [==============================] - 0s 445us/step - loss: 0.5404 - accuracy: 0.7368
Epoch 33/100
804/804 [==============================] - 0s 436us/step - loss: 0.5398 - accuracy: 0.7374
Epoch 34/100
804/804 [==============================] - 0s 436us/step - loss: 0.5398 - accuracy: 0.7365
Epoch 35/100
804/804 [==============================] - 0s 433us/step - loss: 0.5395 - accuracy: 0.7376
Epoch 36/100
804/804 [==============================] - 0s 469us/step - loss: 0.5396 - accuracy: 0.7368
Epoch 37/100
804/804 [==============================] - 0s 436us/step - loss: 0.5392 - accuracy: 0.7369
Epoch 38/100
804/804 [==============================] - 0s 452us/step - loss: 0.5395 - accuracy: 0.7364
Epoch 39/100
804/804 [==============================] - 0s 433us/step - loss: 0.5392 - accuracy: 0.7376
Epoch 40/100
804/804 [==============================] - 0s 432us/step - loss: 0.5389 - accuracy: 0.7376
Epoch 41/100
804/804 [==============================] - 0s 434us/step - loss: 0.5387 - accuracy: 0.7376
Epoch 42/100
804/804 [==============================] - 0s 442us/step - loss: 0.5386 - accuracy: 0.7386
Epoch 43/100
804/804 [==============================] - 0s 468us/step - loss: 0.5386 - accuracy: 0.7379
Epoch 44/100
804/804 [==============================] - 0s 437us/step - loss: 0.5387 - accuracy: 0.7379
Epoch 45/100
804/804 [==============================] - 0s 437us/step - loss: 0.5384 - accuracy: 0.7386
Epoch 46/100
804/804 [==============================] - 0s 433us/step - loss: 0.5385 - accuracy: 0.7363
Epoch 47/100
804/804 [==============================] - 0s 434us/step - loss: 0.5383 - accuracy: 0.7383
Epoch 48/100
804/804 [==============================] - 0s 438us/step - loss: 0.5384 - accuracy: 0.7384
Epoch 49/100
804/804 [==============================] - 0s 437us/step - loss: 0.5378 - accuracy: 0.7380
Epoch 50/100
804/804 [==============================] - 0s 471us/step - loss: 0.5378 - accuracy: 0.7375
Epoch 51/100
804/804 [==============================] - 0s 435us/step - loss: 0.5378 - accuracy: 0.7386
Epoch 52/100
804/804 [==============================] - 0s 438us/step - loss: 0.5376 - accuracy: 0.7386
Epoch 53/100
804/804 [==============================] - 0s 435us/step - loss: 0.5374 - accuracy: 0.7379
Epoch 54/100
804/804 [==============================] - 0s 435us/step - loss: 0.5373 - accuracy: 0.7387
Epoch 55/100
804/804 [==============================] - 0s 436us/step - loss: 0.5375 - accuracy: 0.7382
Epoch 56/100
804/804 [==============================] - 0s 436us/step - loss: 0.5371 - accuracy: 0.7385
Epoch 57/100
804/804 [==============================] - 0s 471us/step - loss: 0.5366 - accuracy: 0.7388
Epoch 58/100
804/804 [==============================] - 0s 439us/step - loss: 0.5372 - accuracy: 0.7393
Epoch 59/100
804/804 [==============================] - 0s 436us/step - loss: 0.5369 - accuracy: 0.7392
Epoch 60/100
804/804 [==============================] - 0s 438us/step - loss: 0.5373 - accuracy: 0.7382
Epoch 61/100
804/804 [==============================] - 0s 435us/step - loss: 0.5368 - accuracy: 0.7390
Epoch 62/100
804/804 [==============================] - 0s 435us/step - loss: 0.5370 - accuracy: 0.7393
Epoch 63/100
804/804 [==============================] - 0s 437us/step - loss: 0.5363 - accuracy: 0.7385
Epoch 64/100
804/804 [==============================] - 0s 464us/step - loss: 0.5367 - accuracy: 0.7384
Epoch 65/100
804/804 [==============================] - 0s 440us/step - loss: 0.5365 - accuracy: 0.7392
Epoch 66/100
804/804 [==============================] - 0s 425us/step - loss: 0.5364 - accuracy: 0.7396
Epoch 67/100
804/804 [==============================] - 0s 448us/step - loss: 0.5365 - accuracy: 0.7385
Epoch 68/100
804/804 [==============================] - 0s 432us/step - loss: 0.5362 - accuracy: 0.7397
Epoch 69/100
804/804 [==============================] - 0s 432us/step - loss: 0.5360 - accuracy: 0.7390
Epoch 70/100
804/804 [==============================] - 0s 463us/step - loss: 0.5363 - accuracy: 0.7393
Epoch 71/100
804/804 [==============================] - 0s 437us/step - loss: 0.5358 - accuracy: 0.7398
Epoch 72/100
804/804 [==============================] - 0s 437us/step - loss: 0.5357 - accuracy: 0.7396
Epoch 73/100
804/804 [==============================] - 0s 434us/step - loss: 0.5358 - accuracy: 0.7399
Epoch 74/100
804/804 [==============================] - 0s 436us/step - loss: 0.5361 - accuracy: 0.7392
Epoch 75/100
804/804 [==============================] - 0s 437us/step - loss: 0.5351 - accuracy: 0.7394
Epoch 76/100
804/804 [==============================] - 0s 433us/step - loss: 0.5361 - accuracy: 0.7390
Epoch 77/100
804/804 [==============================] - 0s 465us/step - loss: 0.5360 - accuracy: 0.7391
Epoch 78/100
804/804 [==============================] - 0s 435us/step - loss: 0.5353 - accuracy: 0.7392
Epoch 79/100
804/804 [==============================] - 0s 433us/step - loss: 0.5354 - accuracy: 0.7392
Epoch 80/100
804/804 [==============================] - 0s 437us/step - loss: 0.5352 - accuracy: 0.7390
Epoch 81/100
804/804 [==============================] - 0s 441us/step - loss: 0.5353 - accuracy: 0.7393
Epoch 82/100
804/804 [==============================] - 0s 433us/step - loss: 0.5353 - accuracy: 0.7398
Epoch 83/100
804/804 [==============================] - 0s 432us/step - loss: 0.5351 - accuracy: 0.7399
Epoch 84/100
804/804 [==============================] - 0s 463us/step - loss: 0.5349 - accuracy: 0.7393
Epoch 85/100
804/804 [==============================] - 0s 432us/step - loss: 0.5353 - accuracy: 0.7403
Epoch 86/100
804/804 [==============================] - 0s 434us/step - loss: 0.5349 - accuracy: 0.7401
Epoch 87/100
804/804 [==============================] - 0s 439us/step - loss: 0.5346 - accuracy: 0.7406
Epoch 88/100
804/804 [==============================] - 0s 438us/step - loss: 0.5347 - accuracy: 0.7390
Epoch 89/100
804/804 [==============================] - 0s 434us/step - loss: 0.5346 - accuracy: 0.7399
Epoch 90/100
804/804 [==============================] - 0s 468us/step - loss: 0.5347 - accuracy: 0.7396
Epoch 91/100
804/804 [==============================] - 0s 437us/step - loss: 0.5340 - accuracy: 0.7399
Epoch 92/100
804/804 [==============================] - 0s 434us/step - loss: 0.5346 - accuracy: 0.7398
Epoch 93/100
804/804 [==============================] - 0s 436us/step - loss: 0.5349 - accuracy: 0.7393
Epoch 94/100
804/804 [==============================] - 0s 436us/step - loss: 0.5348 - accuracy: 0.7398
Epoch 95/100
804/804 [==============================] - 0s 435us/step - loss: 0.5346 - accuracy: 0.7397
Epoch 96/100
804/804 [==============================] - 0s 449us/step - loss: 0.5344 - accuracy: 0.7404
Epoch 97/100
804/804 [==============================] - 0s 466us/step - loss: 0.5347 - accuracy: 0.7399
Epoch 98/100
804/804 [==============================] - 0s 437us/step - loss: 0.5343 - accuracy: 0.7397
Epoch 99/100
804/804 [==============================] - 0s 437us/step - loss: 0.5347 - accuracy: 0.7406
Epoch 100/100
804/804 [==============================] - 0s 437us/step - loss: 0.5343 - accuracy: 0.7394

In [15]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5613 - accuracy: 0.7279 - 189ms/epoch - 705us/step
Loss: 0.5612838268280029, Accuracy: 0.7279300093650818

In [18]:
import os
# Specify the directory path where you want to save the model
directory_path = "/Users/ismailellahi/Desktop/BootCamp/Homework/Module 21/deep-learning-challenge"

# Make sure the directory exists, or create it if it doesn't
if not os.path.exists(directory_path):
    os.makedirs(directory_path)

# Save the model to the HDF5 file in the specified directory
model_filename = os.path.join(directory_path, "AlphabetSoupCharity.h5")
nn.save(model_filename)

# Print a confirmation message
print(f"Model saved to {model_filename}")

Model saved to /Users/ismailellahi/Desktop/BootCamp/Homework/Module 21/deep-learning-challenge/AlphabetSoupCharity.h5

/Users/ismailellahi/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(